# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  az2003v2:
    image: az2003v2
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
